import { useState, MouseEvent } from 'react';

// material-ui
import Stack from '@mui/material/Stack';
import Typography from '@mui/material/Typography';
import MainCard from 'components/MainCard';
import ApexLineChart from './ApexLineChart';
import { Grid } from '@mui/material';
import { width } from '@mui/system';
import { formatDollar } from 'utils/trimFc';
import ThemeButton from 'components/ui/Button';
import { PreviewIcon } from 'assets/svg/preview';

// ==============================|| CHART - REPEAT CUSTOMER RATE ||============================== //

const LineChartMain = ({ commission }: any) => {
  return (
    <>
      <Stack direction={'row'} width={'100%'} gap={3} alignItems={'start'}>
        <MainCard style={{ boxShadow: '0px 2px 10px rgba(0, 0, 0, 0.1)', width: '73.5%' }}>
          <Stack direction="row" alignItems="center" justifyContent="space-between" spacing={1}>
            <Stack>
              <Typography variant="h5" color={'#535E6F'}>
                Revenue generated
              </Typography>
              <Typography variant="caption" color={'#7A839D'}>
                Total amount of revenue generated by month
              </Typography>
            </Stack>
          </Stack>

          <ApexLineChart commission={commission} />
        </MainCard>
      </Stack>
    </>
  );
};
export default LineChartMain;
